events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;

    # FRONTEND
    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
    }

    # NAKAMA API
    location /v2/ {
      proxy_pass http://nakama:7350;
      proxy_set_header Host $host;
    }

    # WEBSOCKET
    location /ws {
      proxy_pass http://nakama:7350;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }
  }
}