services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
    ports:
      - "5432:5432"

  nakama:
    image: heroiclabs/nakama:3.22.0
    depends_on:
      - postgres
    volumes:
      - ../../apps/server/nakama/modules:/nakama/data/modules
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - |
        echo "Waiting for Postgres..."
        until /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama; do
          echo "Retrying DB connection..."
          sleep 2
        done  

        exec /nakama/nakama \
          --name nakama1 \
          --database.address postgres:localdb@postgres:5432/nakama \
          --logger.level DEBUG \
          --console.username admin \
          --console.password password \
          --runtime.js_entrypoint "match_handler.js"
    ports:
      - "7350:7350"
      - "7351:7351"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../../apps/web/dist:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nakama